# Generated by Django 4.1 on 2023-08-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="confidence",
            field=models.IntegerField(
                default=1, verbose_name=[(1, "Weak"), (2, "Medium"), (3, "Strong")]
            ),
        ),
    ]
