# Generated by Django 4.1 on 2023-08-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_card_answer_photo_card_question_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card", old_name="answer_photo", new_name="answer_image",
        ),
        migrations.RenameField(
            model_name="card", old_name="question_photo", new_name="question_image",
        ),
    ]
